stages:
  - test
  - build
  - mirror

before_script:
  - npm install

unit_test:
  stage: test
  script:
    - npm test
  except:
    - master
  tags:
    - shell

build_prod:
  stage: build
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
    - src/script/build/nativetable.min.js
  tags:
    - shell

update_github:
  stage: mirror
  script:
    - git remote add github git@github.com:Mindsers/nativetable.git
    - git push github master
  only:
    - master
  tags:
    - shell
