image: node:latest

stages:
  - test
  - build
  - mirror

before_script:
  - npm install

unit_test:
  stage: test
  script:
    - npm test
  tags:
    - nodejs

build_prod:
  stage: build
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
    - dist/nativetable.min.js
  tags:
    - nodejs
