language: node_js
node_js:
  - "6"

install:
  - npm install

script:
  - npm run test:lint
  - npm test
  
before_deploy:
  - npm run build

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    branch: master 
    tags: true
